export enum ExpenseChartGroupBy {
  EXPENSE_CATEGORY = 'EXPENSE_CATEGORY',
  EXPENSE_CREDIT_CARD = 'EXPENSE_CREDIT_CARD',
  EXPENSE_FORM_OF_PAYMENT = 'EXPENSE_FORM_OF_PAYMENT',
  EXPENSE_BANK_ACCOUNT = 'EXPENSE_BANK_ACCOUNT',
}
