export enum FilterField {
  CREDIT_CARD = 'CREDIT_CARD',
  AMOUNT = 'AMOUNT',
  BANK_ACCOUNT = 'BANK_ACCOUNT',
  EXPENSE_DATE = 'EXPENSE_DATE',
  FORM_OF_PAYMENT = 'FORM_OF_PAYMENT',
  EXPENSE_CATEGORY = 'EXPENSE_CATEGORY',
  DESCRIPTION = 'DESCRIPTION',
  INCOME_DATE = 'INCOME_DATE',
}
